# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test"
  lane :test do
    run_tests(device: "iPhone 13",
    scheme: "WhereIsMyMusic")
  end

  desc "Upload to Testflight"
  lane :beta do |options|
    if options[:v]
      increment_build_number(xcodeproj: "WhereIsMyMusic.xcodeproj",
      build_number: options[:v])
      build_app(scheme: "WhereIsMyMusic")
      upload_to_testflight
      slack(message: "Successfully uploaded beta version. Add information to distribute on Testflight.")
    end
  end
  
  desc "Release new version to App Store"
  lane :release do |options|
    if options[:v]  
      increment_build_number(xcodeproj: "WhereIsMyMusic.xcodeproj",
      build_number: options[:v])
      build_app(scheme: "WhereIsMyMusic")
      upload_to_app_store
      slack(message: "Successfully uploaded release version on App Store Connect. Fill out additional information.")
    end
  end
  
end  
